name: Python Mutation Testing Pipeline
description: Run mutation tests on latest commit changes using the current test suite
on:
  push:
    # This will trigger the workflow for push events to any branch
  pull_request:
    # This will trigger the workflow for pull request events targeting any branch

jobs:
  test:
    runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0 # Fetch all history for all tags and branches

        - name: Set up Python >= 3.8
          uses: actions/setup-python@v2
          with:
            python-version: '3.9' # Use the version of Python required by the project

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov

        - name: Clone Mutatest repository
          run: git clone https://github.com/meghansh36/mutatest

        - name: Run Mutatest with pytest
          run: |
            python3 ./mutatest/cli.py -s fastapi/fastapi/ -t "pytest --cov=fastapi/fastapi --cov-report=term --cov-report=html fastapi/tests --ignore=fastapi/tests/test_tutorial"